// Player list for T20 World Cup 2026 - Official Squads
export const allPlayers = {
  India: [
    { id: 1, name: "Suryakumar Yadav", role: "batsman" },
    { id: 2, name: "Abhishek Sharma", role: "batsman" },
    { id: 3, name: "Tilak Varma", role: "batsman" },
    { id: 4, name: "Sanju Samson", role: "batsman" },
    { id: 5, name: "Shivam Dube", role: "batsman" },
    { id: 6, name: "Ishan Kishan", role: "batsman" },
    { id: 7, name: "Hardik Pandya", role: "batsman" },
    { id: 8, name: "Rinku Singh", role: "batsman" },
    { id: 9, name: "Jasprit Bumrah", role: "bowler" },
    { id: 10, name: "Arshdeep Singh", role: "bowler" },
    { id: 11, name: "Harshit Rana", role: "bowler" },
    { id: 12, name: "Varun Chakaravarthy", role: "bowler" },
    { id: 13, name: "Kuldeep Yadav", role: "bowler" },
    { id: 14, name: "Axar Patel", role: "bowler" },
    { id: 15, name: "Washington Sundar", role: "bowler" }
  ],
  Pakistan: [
    { id: 16, name: "Salman Ali Agha", role: "batsman" },
    { id: 17, name: "Babar Azam", role: "batsman" },
    { id: 18, name: "Fakhar Zaman", role: "batsman" },
    { id: 19, name: "Saim Ayub", role: "batsman" },
    { id: 20, name: "Khawaja Mohammad Nafay", role: "batsman" },
    { id: 21, name: "Sahibzada Farhan", role: "batsman" },
    { id: 22, name: "Faheem Ashraf", role: "batsman" },
    { id: 23, name: "Usman Khan", role: "batsman" },
    { id: 24, name: "Shaheen Shah Afridi", role: "bowler" },
    { id: 25, name: "Naseem Shah", role: "bowler" },
    { id: 26, name: "Abrar Ahmed", role: "bowler" },
    { id: 27, name: "Mohammad Nawaz", role: "bowler" },
    { id: 28, name: "Shadab Khan", role: "bowler" },
    { id: 29, name: "Usman Tariq", role: "bowler" },
    { id: 30, name: "Mohammad Salman Mirza", role: "bowler" }
  ],
  Australia: [
    { id: 31, name: "Mitchell Marsh", role: "batsman" },
    { id: 32, name: "Travis Head", role: "batsman" },
    { id: 33, name: "Matthew Renshaw", role: "batsman" },
    { id: 34, name: "Glenn Maxwell", role: "batsman" },
    { id: 35, name: "Tim David", role: "batsman" },
    { id: 36, name: "Josh Inglis", role: "batsman" },
    { id: 37, name: "Marcus Stoinis", role: "batsman" },
    { id: 38, name: "Cooper Connolly", role: "batsman" },
    { id: 39, name: "Cameron Green", role: "bowler" },
    { id: 40, name: "Nathan Ellis", role: "bowler" },
    { id: 41, name: "Ben Dwarshuis", role: "bowler" },
    { id: 42, name: "Matthew Kuhnemann", role: "bowler" },
    { id: 43, name: "Adam Zampa", role: "bowler" },
    { id: 44, name: "Xavier Bartlett", role: "bowler" },
    { id: 45, name: "Sean Abbott", role: "bowler" }
  ],
  "South Africa": [
    { id: 46, name: "Aiden Markram", role: "batsman" },
    { id: 47, name: "Reeza Hendricks", role: "batsman" },
    { id: 48, name: "Quinton de Kock", role: "batsman" },
    { id: 49, name: "David Miller", role: "batsman" },
    { id: 50, name: "Tristan Stubbs", role: "batsman" },
    { id: 51, name: "Ryan Rickelton", role: "batsman" },
    { id: 52, name: "Dewald Brevis", role: "batsman" },
    { id: 53, name: "Jason Smith", role: "batsman" },
    { id: 54, name: "Anrich Nortje", role: "bowler" },
    { id: 55, name: "Kagiso Rabada", role: "bowler" },
    { id: 56, name: "Lungi Ngidi", role: "bowler" },
    { id: 57, name: "Keshav Maharaj", role: "bowler" },
    { id: 58, name: "Marco Jansen", role: "bowler" },
    { id: 59, name: "Corbin Bosch", role: "bowler" },
    { id: 60, name: "Kwena Maphaka", role: "bowler" }
  ],
  England: [
    { id: 61, name: "Harry Brook", role: "batsman" },
    { id: 62, name: "Jos Buttler", role: "batsman" },
    { id: 63, name: "Ben Duckett", role: "batsman" },
    { id: 64, name: "Jacob Bethell", role: "batsman" },
    { id: 65, name: "Will Jacks", role: "batsman" },
    { id: 66, name: "Tom Banton", role: "batsman" },
    { id: 67, name: "Phil Salt", role: "batsman" },
    { id: 68, name: "Sam Curran", role: "batsman" },
    { id: 69, name: "Jofra Archer", role: "bowler" },
    { id: 70, name: "Adil Rashid", role: "bowler" },
    { id: 71, name: "Josh Tongue", role: "bowler" },
    { id: 72, name: "Rehan Ahmed", role: "bowler" },
    { id: 73, name: "Liam Dawson", role: "bowler" },
    { id: 74, name: "Jamie Overton", role: "bowler" },
    { id: 75, name: "Luke Wood", role: "bowler" }
  ],
  "West Indies": [
    { id: 76, name: "Shai Hope", role: "batsman" },
    { id: 77, name: "Shimron Hetmyer", role: "batsman" },
    { id: 78, name: "Roston Chase", role: "batsman" },
    { id: 79, name: "Johnson Charles", role: "batsman" },
    { id: 80, name: "Brandon King", role: "batsman" },
    { id: 81, name: "Rovman Powell", role: "batsman" },
    { id: 82, name: "Sherfane Rutherford", role: "batsman" },
    { id: 83, name: "Gudakesh Motie", role: "batsman" },
    { id: 84, name: "Romario Shepherd", role: "bowler" },
    { id: 85, name: "Akeal Hosein", role: "bowler" },
    { id: 86, name: "Shamar Joseph", role: "bowler" },
    { id: 87, name: "Matthew Forde", role: "bowler" },
    { id: 88, name: "Jason Holder", role: "bowler" },
    { id: 89, name: "Jayden Seales", role: "bowler" },
    { id: 90, name: "Quentin Sampson", role: "bowler" }
  ],
  "Sri Lanka": [
    { id: 91, name: "Dasun Shanaka", role: "batsman" },
    { id: 92, name: "Pathum Nissanka", role: "batsman" },
    { id: 93, name: "Kamindu Mendis", role: "batsman" },
    { id: 94, name: "Kusal Mendis", role: "batsman" },
    { id: 95, name: "Charith Asalanka", role: "batsman" },
    { id: 96, name: "Kusal Janith Perera", role: "batsman" },
    { id: 97, name: "Kamil Mishara", role: "batsman" },
    { id: 98, name: "Janith Liyanage", role: "batsman" },
    { id: 99, name: "Wanindu Hasaranga", role: "bowler" },
    { id: 100, name: "Maheesh Theekshana", role: "bowler" },
    { id: 101, name: "Matheesha Pathirana", role: "bowler" },
    { id: 102, name: "Dushmantha Chameera", role: "bowler" },
    { id: 103, name: "Dunith Wellalage", role: "bowler" },
    { id: 104, name: "Pavan Rathnayake", role: "bowler" },
    { id: 105, name: "Eshan Malinga", role: "bowler" }
  ],
  Afghanistan: [
    { id: 106, name: "Rashid Khan", role: "batsman" },
    { id: 107, name: "Mohammad Nabi", role: "batsman" },
    { id: 108, name: "Rahmanullah Gurbaz", role: "batsman" },
    { id: 109, name: "Ibrahim Zadran", role: "batsman" },
    { id: 110, name: "Azmatullah Omarzai", role: "batsman" },
    { id: 111, name: "Gulbadin Naib", role: "batsman" },
    { id: 112, name: "Sediqullah Atal", role: "batsman" },
    { id: 113, name: "Abdullah Ahmadzai", role: "batsman" },
    { id: 114, name: "Naveen Ul Haq", role: "bowler" },
    { id: 115, name: "Mujeeb Ur Rahman", role: "bowler" },
    { id: 116, name: "Fazalhaq Farooqi", role: "bowler" },
    { id: 117, name: "Noor Ahmad", role: "bowler" },
    { id: 118, name: "Mohammad Ishaq", role: "bowler" },
    { id: 119, name: "Darwish Rasooli", role: "bowler" },
    { id: 120, name: "Shahidullah Kamal", role: "bowler" }
  ],
  "New Zealand": [
    { id: 121, name: "Mitchell Santner", role: "batsman" },
    { id: 122, name: "Finn Allen", role: "batsman" },
    { id: 123, name: "Devon Conway", role: "batsman" },
    { id: 124, name: "Mark Chapman", role: "batsman" },
    { id: 125, name: "Daryl Mitchell", role: "batsman" },
    { id: 126, name: "Michael Bracewell", role: "batsman" },
    { id: 127, name: "Glenn Phillips", role: "batsman" },
    { id: 128, name: "Tim Seifert", role: "batsman" },
    { id: 129, name: "Lockie Ferguson", role: "bowler" },
    { id: 130, name: "Ish Sodhi", role: "bowler" },
    { id: 131, name: "Matt Henry", role: "bowler" },
    { id: 132, name: "Jacob Duffy", role: "bowler" },
    { id: 133, name: "Kyle Jamieson", role: "bowler" },
    { id: 134, name: "James Neesham", role: "bowler" },
    { id: 135, name: "Rachin Ravindra", role: "bowler" }
  ],
  "United States": [
    { id: 136, name: "Monank Patel", role: "batsman" },
    { id: 137, name: "Andries Gous", role: "batsman" },
    { id: 138, name: "Shehan Jayasuriya", role: "batsman" },
    { id: 139, name: "Milind Kumar", role: "batsman" },
    { id: 140, name: "Jitesh Sharma", role: "batsman" },
    { id: 141, name: "Saiteja Mukkamala", role: "batsman" },
    { id: 142, name: "Shayan Jahangir", role: "batsman" },
    { id: 143, name: "Nosthush Kenjige", role: "batsman" },
    { id: 144, name: "Ali Khan", role: "bowler" },
    { id: 145, name: "Saurabh Netravalkar", role: "bowler" },
    { id: 146, name: "Mohammad Mohsin", role: "bowler" },
    { id: 147, name: "Harmeet Singh", role: "bowler" },
    { id: 148, name: "Shubham Ranjane", role: "bowler" },
    { id: 149, name: "Sanjay Krishnamurthi", role: "bowler" },
    { id: 150, name: "Shadley Van Schalkwyk", role: "bowler" }
  ],
  Scotland: [
    { id: 151, name: "Richie Berrington", role: "batsman" },
    { id: 152, name: "George Munsey", role: "batsman" },
    { id: 153, name: "Matthew Cross", role: "batsman" },
    { id: 154, name: "Brandon McMullen", role: "batsman" },
    { id: 155, name: "Michael Leask", role: "batsman" },
    { id: 156, name: "Oliver Davidson", role: "batsman" },
    { id: 157, name: "Tom Bruce", role: "batsman" },
    { id: 158, name: "Zainullah Ihsan", role: "batsman" },
    { id: 159, name: "Mark Watt", role: "bowler" },
    { id: 160, name: "Safyaan Sharif", role: "bowler" },
    { id: 161, name: "Chris Greaves", role: "bowler" },
    { id: 162, name: "Bradley Wheal", role: "bowler" },
    { id: 163, name: "Michael Jones", role: "bowler" },
    { id: 164, name: "Finlay McCreath", role: "bowler" },
    { id: 165, name: "Bradley Currie", role: "bowler" }
  ],
  Ireland: [
    { id: 166, name: "Paul Stirling", role: "batsman" },
    { id: 167, name: "Harry Tector", role: "batsman" },
    { id: 168, name: "Lorcan Tucker", role: "batsman" },
    { id: 169, name: "Curtis Campher", role: "batsman" },
    { id: 170, name: "Gareth Delany", role: "batsman" },
    { id: 171, name: "Ben White", role: "batsman" },
    { id: 172, name: "Tim Tector", role: "batsman" },
    { id: 173, name: "Matthew Humphreys", role: "batsman" },
    { id: 174, name: "Josh Little", role: "bowler" },
    { id: 175, name: "Mark Adair", role: "bowler" },
    { id: 176, name: "Craig Young", role: "bowler" },
    { id: 177, name: "Barry McCarthy", role: "bowler" },
    { id: 178, name: "George Dockrell", role: "bowler" },
    { id: 179, name: "Ross Adair", role: "bowler" },
    { id: 180, name: "Ben Calitz", role: "bowler" }
  ],
  Namibia: [
    { id: 181, name: "Gerhard Erasmus", role: "batsman" },
    { id: 182, name: "Zane Green", role: "batsman" },
    { id: 183, name: "Ruben Trumpelmann", role: "batsman" },
    { id: 184, name: "Jan Frylinck", role: "batsman" },
    { id: 185, name: "JJ Smit", role: "batsman" },
    { id: 186, name: "Nicol Loftie-Eaton", role: "batsman" },
    { id: 187, name: "Malan Kruger", role: "batsman" },
    { id: 188, name: "Louren Steenkamp", role: "batsman" },
    { id: 189, name: "Bernard Scholtz", role: "bowler" },
    { id: 190, name: "Jack Brassell", role: "bowler" },
    { id: 191, name: "Ben Shikongo", role: "bowler" },
    { id: 192, name: "JC Balt", role: "bowler" },
    { id: 193, name: "Dylan Leicher", role: "bowler" },
    { id: 194, name: "WP Myburgh", role: "bowler" },
    { id: 195, name: "Max Heingo", role: "bowler" }
  ],
  Netherlands: [
    { id: 196, name: "Scott Edwards", role: "batsman" },
    { id: 197, name: "Max O'Dowd", role: "batsman" },
    { id: 198, name: "Bas de Leede", role: "batsman" },
    { id: 199, name: "Colin Ackermann", role: "batsman" },
    { id: 200, name: "Noah Croes", role: "batsman" },
    { id: 201, name: "Michael Levitt", role: "batsman" },
    { id: 202, name: "Kyle Klein", role: "batsman" },
    { id: 203, name: "Zach Lion-Cachet", role: "batsman" },
    { id: 204, name: "Paul van Meekeren", role: "bowler" },
    { id: 205, name: "Roelof van der Merwe", role: "bowler" },
    { id: 206, name: "Fred Klaassen", role: "bowler" },
    { id: 207, name: "Logan van Beek", role: "bowler" },
    { id: 208, name: "Timm van der Gugten", role: "bowler" },
    { id: 209, name: "Aryan Dutt", role: "bowler" },
    { id: 210, name: "Saqib Zulfiqar", role: "bowler" }
  ],
  Zimbabwe: [
    { id: 211, name: "Sikandar Raza", role: "batsman" },
    { id: 212, name: "Brendan Taylor", role: "batsman" },
    { id: 213, name: "Tadiwanashe Marumani", role: "batsman" },
    { id: 214, name: "Wellington Masakadza", role: "batsman" },
    { id: 215, name: "Clive Madande", role: "batsman" },
    { id: 216, name: "Brian Bennett", role: "batsman" },
    { id: 217, name: "Ryan Burl", role: "batsman" },
    { id: 218, name: "Dion Myers", role: "batsman" },
    { id: 219, name: "Blessing Muzarabani", role: "bowler" },
    { id: 220, name: "Richard Ngarava", role: "bowler" },
    { id: 221, name: "Graeme Cremer", role: "bowler" },
    { id: 222, name: "Tony Munyonga", role: "bowler" },
    { id: 223, name: "Tashinga Musekiwa", role: "bowler" },
    { id: 224, name: "Tinotenda Maposa", role: "bowler" },
    { id: 225, name: "Bradley Evans", role: "bowler" }
  ],
  Oman: [
    { id: 226, name: "Jatinder Singh", role: "batsman" },
    { id: 227, name: "Vinayak Shukla", role: "batsman" },
    { id: 228, name: "Mohammad Nadeem", role: "batsman" },
    { id: 229, name: "Hammad Mirza", role: "batsman" },
    { id: 230, name: "Wasim Ali", role: "batsman" },
    { id: 231, name: "Shakeel Ahmad", role: "batsman" },
    { id: 232, name: "Shah Faisal", role: "batsman" },
    { id: 233, name: "Nadeem Khan", role: "batsman" },
    { id: 234, name: "Sufyan Mehmood", role: "bowler" },
    { id: 235, name: "Karan Sonavale", role: "bowler" },
    { id: 236, name: "Jay Odedra", role: "bowler" },
    { id: 237, name: "Shafiq Jan", role: "bowler" },
    { id: 238, name: "Ashish Odedara", role: "bowler" },
    { id: 239, name: "Jiten Ramanandi", role: "bowler" },
    { id: 240, name: "Hasnain Ali Shah", role: "bowler" }
  ],
  Canada: [
    { id: 241, name: "Dilpreet Bajwa", role: "batsman" },
    { id: 242, name: "Saad Bin Zafar", role: "batsman" },
    { id: 243, name: "Ajayveer Hundal", role: "batsman" },
    { id: 244, name: "Harsh Thaker", role: "batsman" },
    { id: 245, name: "Kanwarpal Tathgur", role: "batsman" },
    { id: 246, name: "Nikhil Dutta", role: "batsman" },
    { id: 247, name: "Ansh Patel", role: "batsman" },
    { id: 248, name: "Navneet Dhaliwal", role: "batsman" },
    { id: 249, name: "Kaleem Sana", role: "bowler" },
    { id: 250, name: "Jaskarandeep Buttar", role: "bowler" },
    { id: 251, name: "Shreyas Movva", role: "bowler" },
    { id: 252, name: "Shivam Sharma", role: "bowler" },
    { id: 253, name: "Ravinderpal Singh", role: "bowler" },
    { id: 254, name: "Dilon Heyliger", role: "bowler" },
    { id: 255, name: "Yuvraj Samra", role: "bowler" }
  ],
  Nepal: [
    { id: 256, name: "Rohit Paudel", role: "batsman" },
    { id: 257, name: "Dipendra Singh Airee", role: "batsman" },
    { id: 258, name: "Aasif Sheikh", role: "batsman" },
    { id: 259, name: "Kushal Bhurtel", role: "batsman" },
    { id: 260, name: "Sundeep Jora", role: "batsman" },
    { id: 261, name: "Aarif Sheikh", role: "batsman" },
    { id: 262, name: "Basir Ahamad", role: "batsman" },
    { id: 263, name: "Sher Malla", role: "batsman" },
    { id: 264, name: "Sompal Kami", role: "bowler" },
    { id: 265, name: "Sandeep Lamichhane", role: "bowler" },
    { id: 266, name: "Karan KC", role: "bowler" },
    { id: 267, name: "Nandan Yadav", role: "bowler" },
    { id: 268, name: "Gulshan Jha", role: "bowler" },
    { id: 269, name: "Lalit Rajbanshi", role: "bowler" },
    { id: 270, name: "Lokesh Bam", role: "bowler" }
  ],
  Italy: [
    { id: 271, name: "Wayne Madsen", role: "batsman" },
    { id: 272, name: "Marcus Campopiano", role: "batsman" },
    { id: 273, name: "Gian Piero Meade", role: "batsman" },
    { id: 274, name: "Ali Hasan", role: "batsman" },
    { id: 275, name: "Zain Ali", role: "batsman" },
    { id: 276, name: "Crishan Jorge", role: "batsman" },
    { id: 277, name: "Harry Manenti", role: "batsman" },
    { id: 278, name: "Anthony Mosca", role: "batsman" },
    { id: 279, name: "Jaspreet Singh", role: "bowler" },
    { id: 280, name: "Justin Mosca", role: "bowler" },
    { id: 281, name: "Grant Stewart", role: "bowler" },
    { id: 282, name: "Benjamin Manenti", role: "bowler" },
    { id: 283, name: "Syed Naqvi", role: "bowler" },
    { id: 284, name: "JJ Smuts", role: "bowler" },
    { id: 285, name: "Thomas Draca", role: "bowler" }
  ],
  "United Arab Emirates": [
    { id: 286, name: "Muhammad Waseem", role: "batsman" },
    { id: 287, name: "Alishan Sharafu", role: "batsman" },
    { id: 288, name: "Aryansh Sharma", role: "batsman" },
    { id: 289, name: "Haider Ali", role: "batsman" },
    { id: 290, name: "Dhruv Parashar", role: "batsman" },
    { id: 291, name: "Harshit Kaushik", role: "batsman" },
    { id: 292, name: "Junaid Siddique", role: "batsman" },
    { id: 293, name: "Mayank Kumar", role: "batsman" },
    { id: 294, name: "Rohid Khan", role: "bowler" },
    { id: 295, name: "Muhammad Arfan", role: "bowler" },
    { id: 296, name: "Muhammad Farooq", role: "bowler" },
    { id: 297, name: "Simranjeet Singh", role: "bowler" },
    { id: 298, name: "Muhammad Jawadullah", role: "bowler" },
    { id: 299, name: "Muhammad Zohaib", role: "bowler" },
    { id: 300, name: "Sohaib Khan", role: "bowler" }
  ]
}
